config/routes.rb
Rails.application.routes.draw do

  root to: 'main_pages#index'

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_validation :titleize

  validates :email, 
    presence: true, #поле не пусто
    uniqueness: true,
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i } #символы, @, символы, . , символы 

  validates :tag,
    presence: true,
    uniqueness: true,
    length: { in: 3..20 },
    format: { without: /\s/ } #нельзя использовать пробел

  validates :name,
    presence: true,
    uniqueness: true,
    format: { with: /\A[A-Z][a-z]*( [A-Z][a-z]*)?\z/ }, #первая буква всегда заглавная а остальные строчные, и допускается исп двух слов
    length: { in: 3..16 }

  validates :password,
    format: { with: /\A(?=.*[A-Z])(?=.*\d)[^ ]+\z/ } #хотя бы одна заглавная и хотя бы одна цифра и нет пробелов

  def titleize
    self.name = name.to_s.split.map(&:capitalize).join(' ')
    self.tag = tag.to_s.split.map(&:capitalize).join(' ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  private

 # фунция которая определяен айди юзера с нынешней сиссии или возвращает нил елси это гость (||= или равно)
  def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    # &. помогает не ловить ошибку если user == nill
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'User signed in'
    else
      flash.now[:error] = 'Invalid email or password'
      render :new, status: 422
    end
  end

  def destroy
    session.delete(:user_id)

    flash[:notice] = 'User logged out'
    redirect_to action: "new"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :email, :tag, :password, :password_confirmation)

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: 'User signed up'
    else

      #@user.errors.full_messages.each do |message|
      #  flash.now[:error] = message
      #end

      flash.now[:error] = @user.errors.full_messages

      render :new, status: 422

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def wrapper_class
    if controller_name == 'sessions' or controller_name == 'users' && action_name == 'show'
      'wrapper_sign_in_up'
    else
      'wrapper'
    end
  end
  
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_class(flash_key)
    case flash_key.to_sym
    when :error
      "bg-error"
    else
      "bg-w"
    end 
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div data-controller="flash" class="center-h mt-m">
    <div class=" <%= flash_class(key) %> cl-b text-sm fixed pd-5-10 center">
      <div>
        <%= value %>
      </div>

      <button data-action="flash#dismiss" type="button" class="ml-10 center-v button-flash">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" width="17" height="17">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render partial: "layouts/flash" %>
    <%= yield %>
  </body>

</html>

app/views/main_pages/index.html.erb
<div class="container">
  <% if current_user.present? %>
    <div class="mh-a cl-w">
      <%=  current_user.name %>
    </div>

    <div class="mh-a">
      <%= button_to 'Sign out', session_path, method: :delete %>
    </div>

  <% else %>
    <p>
      <%= link_to 'Sign up', new_user_path %>
    </p>

    <p>
      <%= link_to 'Sign in', new_session_path %>
    </p>

  <% end %>
</div>

app/views/users/new.html.erb
<div class="container_sign center-v-fixed"> 
    <%= form_with model: @user do |form| %>
      <div class="tittle-lg center-h">
        <div class="cl-w">Tag</div>
        <div class="cl-g">IT</div>  
      </div>

      <p><%= form.text_field :name, placeholder: 'Name', class: 'input_sign tittle-sm mt-lg ' %></p>

      <p><%= form.text_field :email, placeholder: 'Email', class: 'input_sign tittle-sm mt-sm '%></p>

      <p><%= form.text_field :tag, placeholder: 'Tag', class: 'input_sign tittle-sm mt-sm ' %></p>

      <p><%= form.password_field :password, placeholder: 'Password', class: 'input_sign tittle-sm mt-sm ' %></p>

      <p><%= form.password_field :password_confirmation, placeholder: 'Repeat password', class: 'input_sign tittle-sm mt-sm ' %></p>

      <p><%= form.submit "Sign Up", class: 'button_sign mt-lg tittle-m' %></p>

      <p class="center-h mt-ssm mb-ssm">
        <span class="line-125 line-l"></span><span class="mv-a text-m cl-g">or</span><span class="line-125 line-r"></span>
      </p>

      <%= link_to 'Sign in', new_session_path, class: 'cl-w text-m center-h' %>
    <% end %>
</div>